# Generated by Django 6.0.3 on 2026-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sku', 'size'],
                'unique_together': {('sku', 'size')},
            },
        ),
    ]
